"""empty message

Revision ID: 108027d5386d
Revises: bd36dd767caa
Create Date: 2020-04-21 17:19:34.669684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108027d5386d'
down_revision = 'bd36dd767caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
